//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL_NFE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeWEB/services/NfeRecepcao.asmx")]
        public string CL_NFE_HomologRecepcao_NfeRecepcao {
            get {
                return ((string)(this["CL_NFE_HomologRecepcao_NfeRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeWEB/services/NfeRetRecepcao.asmx")]
        public string CL_NFE_HomologRetRecepcao_NfeRetRecepcao {
            get {
                return ((string)(this["CL_NFE_HomologRetRecepcao_NfeRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeWEB/services/NfeRecepcao.asmx")]
        public string CL_NFE_ProducaoRecepcao_NfeRecepcao {
            get {
                return ((string)(this["CL_NFE_ProducaoRecepcao_NfeRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeWEB/services/NfeRetRecepcao.asmx")]
        public string CL_NFE_ProducaoRetRecepcao_NfeRetRecepcao {
            get {
                return ((string)(this["CL_NFE_ProducaoRetRecepcao_NfeRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeWEB/services/NfeCancelamento.asmx")]
        public string CL_NFE_ProducaoCancelamento_NfeCancelamento {
            get {
                return ((string)(this["CL_NFE_ProducaoCancelamento_NfeCancelamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeWEB/services/NfeCancelamento.asmx")]
        public string CL_NFE_HomologCancelamento_NfeCancelamento {
            get {
                return ((string)(this["CL_NFE_HomologCancelamento_NfeCancelamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeCancelamento2/NfeCancelamento2.asmx")]
        public string CL_NFE_SCANHomologCancelamento_NfeCancelamento {
            get {
                return ((string)(this["CL_NFE_SCANHomologCancelamento_NfeCancelamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeRecepcao2/NfeRecepcao2.asmx")]
        public string CL_NFE_SCANHomologRecepcao_NfeRecepcao {
            get {
                return ((string)(this["CL_NFE_SCANHomologRecepcao_NfeRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeRetRecepcao2/NfeRetRecepcao2.asmx")]
        public string CL_NFE_SCANHomologRetRecepcao_NfeRetRecepcao {
            get {
                return ((string)(this["CL_NFE_SCANHomologRetRecepcao_NfeRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeCancelamento2/NfeCancelamento2.asmx")]
        public string CL_NFE_SCANProducaoCancelamento_NfeCancelamento {
            get {
                return ((string)(this["CL_NFE_SCANProducaoCancelamento_NfeCancelamento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeRecepcao2/NfeRecepcao2.asmx")]
        public string CL_NFE_SCANProducaoRecepcao_NfeRecepcao {
            get {
                return ((string)(this["CL_NFE_SCANProducaoRecepcao_NfeRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeRetRecepcao2/NfeRetRecepcao2.asmx")]
        public string CL_NFE_SCANProducaoRetRecepcao_NfeRetRecepcao {
            get {
                return ((string)(this["CL_NFE_SCANProducaoRetRecepcao_NfeRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeCancelamento2.asmx")]
        public string CL_NFE_HomologCancelamento2_NfeCancelamento2 {
            get {
                return ((string)(this["CL_NFE_HomologCancelamento2_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeRecepcao2.asmx")]
        public string CL_NFE_HomologRetRecepcao2_NfeRecepcao2 {
            get {
                return ((string)(this["CL_NFE_HomologRetRecepcao2_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nfecancelamento2.asmx")]
        public string CL_NFE_ProducaoCancelamento2_NfeCancelamento2 {
            get {
                return ((string)(this["CL_NFE_ProducaoCancelamento2_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nfeautorizacao.asmx")]
        public string CL_NFE_ProducaoRecepcao2_NfeRecepcao2 {
            get {
                return ((string)(this["CL_NFE_ProducaoRecepcao2_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nferetautorizacao.asmx")]
        public string CL_NFE_ProducaoRetRecepcao2_NfeRetRecepcao2 {
            get {
                return ((string)(this["CL_NFE_ProducaoRetRecepcao2_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nferetautorizacao.asmx")]
        public string CL_NFE_HomologRetRecepcao2_NfeRetRecepcao2 {
            get {
                return ((string)(this["CL_NFE_HomologRetRecepcao2_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/recepcaoevento.asmx")]
        public string CL_NFE_HomologacaoCCe_RecepcaoEvento {
            get {
                return ((string)(this["CL_NFE_HomologacaoCCe_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeautorizacao.asmx")]
        public string CL_NFE_HomologRecepcao2_NfeRecepcao2 {
            get {
                return ((string)(this["CL_NFE_HomologRecepcao2_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeCancelamento2/NfeCancelamento2.asmx")]
        public string CL_NFE_SCANHomologCancelamento_NfeCancelamento2 {
            get {
                return ((string)(this["CL_NFE_SCANHomologCancelamento_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeRecepcao2/NfeRecepcao2.asmx")]
        public string CL_NFE_SCANHomologRecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["CL_NFE_SCANHomologRecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeRetRecepcao2/NfeRetRecepcao2.asmx")]
        public string CL_NFE_SCANHomologRetRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["CL_NFE_SCANHomologRetRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.nfe.fazenda.gov.br/SCAN/NfeStatusServico2/NfeStatusServico2.asmx")]
        public string CL_NFE_SCANHomologStatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["CL_NFE_SCANHomologStatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeCancelamento2/NfeCancelamento2.asmx")]
        public string CL_NFE_SCANProducaoCancelamento_NfeCancelamento2 {
            get {
                return ((string)(this["CL_NFE_SCANProducaoCancelamento_NfeCancelamento2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeRecepcao2/NfeRecepcao2.asmx")]
        public string CL_NFE_SCANProducaoRecepcao_NfeRecepcao2 {
            get {
                return ((string)(this["CL_NFE_SCANProducaoRecepcao_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeRetRecepcao2/NfeRetRecepcao2.asmx")]
        public string CL_NFE_SCANProducaoRetRecepcao_NfeRetRecepcao2 {
            get {
                return ((string)(this["CL_NFE_SCANProducaoRetRecepcao_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.scan.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx")]
        public string CL_NFE_SCANProducaoStatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["CL_NFE_SCANProducaoStatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/recepcaoevento.asmx")]
        public string CL_NFE_HomologacaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["CL_NFE_HomologacaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/recepcaoevento.asmx")]
        public string CL_NFE_ProducaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["CL_NFE_ProducaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeinutilizacao4.asmx")]
        public string CL_NFE_nfeinutilizacao4_NFeInutilizacao4 {
            get {
                return ((string)(this["CL_NFE_nfeinutilizacao4_NFeInutilizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeconsultaprotocolo4.asmx")]
        public string CL_NFE_HomoNFeConsultaProtocolo4_NFeConsultaProtocolo4 {
            get {
                return ((string)(this["CL_NFE_HomoNFeConsultaProtocolo4_NFeConsultaProtocolo4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfestatusservico4.asmx")]
        public string CL_NFE_HomoNFeStatusServico4_NFeStatusServico4 {
            get {
                return ((string)(this["CL_NFE_HomoNFeStatusServico4_NFeStatusServico4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/cadconsultacadastro4.asmx")]
        public string CL_NFE_HomoCadConsultaCadastro4_CadConsultaCadastro4 {
            get {
                return ((string)(this["CL_NFE_HomoCadConsultaCadastro4_CadConsultaCadastro4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nferecepcaoevento4.asmx")]
        public string CL_NFE_HomoNFeRecepcaoEvento4_NFeRecepcaoEvento4 {
            get {
                return ((string)(this["CL_NFE_HomoNFeRecepcaoEvento4_NFeRecepcaoEvento4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeautorizacao4.asmx")]
        public string CL_NFE_HomoNFeAutorizacao4_NFeAutorizacao4 {
            get {
                return ((string)(this["CL_NFE_HomoNFeAutorizacao4_NFeAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nferetautorizacao4.asmx")]
        public string CL_NFE_HomoNFeRetAutorizacao4_NFeRetAutorizacao4 {
            get {
                return ((string)(this["CL_NFE_HomoNFeRetAutorizacao4_NFeRetAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nfeinutilizacao4.asmx")]
        public string CL_NFE_ProdNFeInutilizacao4_NFeInutilizacao4 {
            get {
                return ((string)(this["CL_NFE_ProdNFeInutilizacao4_NFeInutilizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nfeconsultaprotocolo4.asmx")]
        public string CL_NFE_ProdNFeConsultaProtocolo4_NFeConsultaProtocolo4 {
            get {
                return ((string)(this["CL_NFE_ProdNFeConsultaProtocolo4_NFeConsultaProtocolo4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nfestatusservico4.asmx")]
        public string CL_NFE_ProdNFeStatusServico4_NFeStatusServico4 {
            get {
                return ((string)(this["CL_NFE_ProdNFeStatusServico4_NFeStatusServico4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/cadconsultacadastro4.asmx")]
        public string CL_NFE_ProdCadConsultaCadastro4_CadConsultaCadastro4 {
            get {
                return ((string)(this["CL_NFE_ProdCadConsultaCadastro4_CadConsultaCadastro4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nferecepcaoevento4.asmx")]
        public string CL_NFE_ProdNFeRecepcaoEvento4_NFeRecepcaoEvento4 {
            get {
                return ((string)(this["CL_NFE_ProdNFeRecepcaoEvento4_NFeRecepcaoEvento4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nfeautorizacao4.asmx")]
        public string CL_NFE_ProdNFeAutorizacao4_NFeAutorizacao4 {
            get {
                return ((string)(this["CL_NFE_ProdNFeAutorizacao4_NFeAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nferetautorizacao4.asmx")]
        public string CL_NFE_ProdNFeRetAutorizacao4_NFeRetAutorizacao4 {
            get {
                return ((string)(this["CL_NFE_ProdNFeRetAutorizacao4_NFeRetAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NFeConsultaProtocolo4/NFeConsultaProtocolo4.asmx")]
        public string CL_NFE_HomoSVCNFeConsultaProtocolo4_NFeConsultaProtocolo4 {
            get {
                return ((string)(this["CL_NFE_HomoSVCNFeConsultaProtocolo4_NFeConsultaProtocolo4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NFeStatusServico4/NFeStatusServico4.asmx")]
        public string CL_NFE_HomoSVCNFeStatusServico4_NFeStatusServico4 {
            get {
                return ((string)(this["CL_NFE_HomoSVCNFeStatusServico4_NFeStatusServico4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx")]
        public string CL_NFE_HomoSVCNFeRecepcaoEvento4_NFeRecepcaoEvento4 {
            get {
                return ((string)(this["CL_NFE_HomoSVCNFeRecepcaoEvento4_NFeRecepcaoEvento4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NFeAutorizacao4/NFeAutorizacao4.asmx")]
        public string CL_NFE_HomoSVCNFeAutorizacao4_NFeAutorizacao4 {
            get {
                return ((string)(this["CL_NFE_HomoSVCNFeAutorizacao4_NFeAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hom.svc.fazenda.gov.br/NFeRetAutorizacao4/NFeRetAutorizacao4.asmx")]
        public string CL_NFE_HomoSVCNFeRetAutorizacao4_NFeRetAutorizacao4 {
            get {
                return ((string)(this["CL_NFE_HomoSVCNFeRetAutorizacao4_NFeRetAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NFeConsultaProtocolo4/NFeConsultaProtocolo4.asmx")]
        public string CL_NFE_ProdSVCNFeConsultaProtocolo4_NFeConsultaProtocolo4 {
            get {
                return ((string)(this["CL_NFE_ProdSVCNFeConsultaProtocolo4_NFeConsultaProtocolo4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NFeStatusServico4/NFeStatusServico4.asmx")]
        public string CL_NFE_ProdSVCNFeStatusServico4_NFeStatusServico4 {
            get {
                return ((string)(this["CL_NFE_ProdSVCNFeStatusServico4_NFeStatusServico4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx")]
        public string CL_NFE_ProdSVCNFeRecepcaoEvento4_NFeRecepcaoEvento4 {
            get {
                return ((string)(this["CL_NFE_ProdSVCNFeRecepcaoEvento4_NFeRecepcaoEvento4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NFeAutorizacao4/NFeAutorizacao4.asmx")]
        public string CL_NFE_ProdSVCNFeAutorizacao4_NFeAutorizacao4 {
            get {
                return ((string)(this["CL_NFE_ProdSVCNFeAutorizacao4_NFeAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.svc.fazenda.gov.br/NFeRetAutorizacao4/NFeRetAutorizacao4.asmx")]
        public string CL_NFE_ProdSVCNFeRetAutorizacao4_NFeRetAutorizacao4 {
            get {
                return ((string)(this["CL_NFE_ProdSVCNFeRetAutorizacao4_NFeRetAutorizacao4"]));
            }
        }
    }
}
